### ISSUE TITLE
[Feature Request] Missing support for unions

### ISSUE THREAD

**Issue by jnv** [superfaceai/one-service#5]
Given a union structure in profile like this:

```
[ string! | number! ]
```

I recieve this exception on one-service start:

```
.../node_modules/@superfaceai/one-service/dist/schema.types.js:235
            throw new Error(`Variable type not implemented for: ${structure.kind}`);
                  ^

Error: Variable type not implemented for: UnionStructure
    at outputType (.../node_modules/@superfaceai/one-service/dist/schema.types.js:235:19)
    at outputType (.../node_modules/@superfaceai/one-service/dist/schema.types.js:231:46)
    at .../node_modules/@superfaceai/one-service/dist/schema.types.js:219:27
    at Array.forEach (<anonymous>)
    at outputType (.../node_modules/@superfaceai/one-service/dist/schema.types.js:217:89)
    at outputType (.../node_modules/@superfaceai/one-service/dist/schema.types.js:231:46)
    at generateStructureResultType (.../node_modules/@superfaceai/one-service/dist/schema.types.js:102:18)
    at generateUseCaseFieldConfig (.../node_modules/@superfaceai/one-service/dist/schema.types.js:60:24)
    at generateProfileTypes (.../node_modules/@superfaceai/one-service/dist/schema.types.js:28:36)
    at generate (.../node_modules/@superfaceai/one-service/dist/schema.js:41:91)
```

## Profile example

```hcl
usecase GetRoomsAvailability {
  input {
    arrivalDate! string!
    departureDate! string!

    "Room/apartment IDs"
    rooms! [string! | number!]
  }

  result [
    {
      date! string!
      availableQuantity! number!
      rooms! [string! | number!]
    }
  ]
}
```

**Comment by freaz** [comment]
For result mapping union shouldn't be a problem. Unfortunately for inputs GraphQL doesn't support unions.

- [Specification](https://spec.graphql.org/October2021/#sec-Unions.Input-Coercion)
- [GitHub Issue](https://github.com/graphql/graphql-spec/issues/488)
